namespace: default
saName: ksrp-expose
appName: ksrp-expose
image: ccr.ccs.tencentyun.com/vizee/ksrp-expose:latest
apiKey: 'abcd'
logLevel: 'info'
service:
  name: ksrp-expose
  linkPort: 5777
  apiPort: 5780
  nodePort: false
